import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Menace!</h1>

        <p className={styles.description}>
          Menace is a fun game. Based on Risk. Player count is 3 to 7.
        </p>

        <div className={styles.grid}>
          <Link href="/rules" className={styles.card}>
            <h2>Rules &rarr;</h2>
            <p>Learn the specifics behind the rules of Menace</p>
          </Link>

          <Link href="/play" className={styles.card}>
            <h2>Play &rarr;</h2>
            <p>Create or join a game. Fun.</p>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
